apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
spec:
  selector:
    app: model-serving
  ports:
    - name: service
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
