apiVersion: v1
kind: Service
metadata:
  name: serving-api-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: serving-api
  ports:
    - name: service
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serving-api-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    # gce: external load balancer
    # gce-internal: internal load balancer
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /v1/*
            pathType: Prefix
            backend:
              service:
                name: serving-api-service
                port:
                  number:
                    8001
          - path: /async/*
            pathType: Prefix
            backend:
              service:
                name: serving-api-service
                port:
                  number:
                    8001
          - path: /task/*
            pathType: Prefix
            backend:
              service:
                name: serving-api-service
                port:
                  number:
                    8001
